[package]
name = "my_first_projects"
version = "0.1.0"
edition = "2024"
default-run = "my_first_projects"

[dependencies]
sha2 = "0.10"
hex = "0.4"
serde ={ version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
